spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/delivery_project?currentSchema=delivery_project}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      #      data-locations: classpath:demo_data.sql
      continue-on-error: false
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: delivery_project
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
security:
  jwt:
    secret: c2VjcmV0aWdpdWhvaWhvdWpvaWpiZ2p5dnViamg=
    access: 3600000
    refresh: 2592000000
springdoc:
  override-with-generic-response: false