spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_project?currentSchema=delivery_project
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
#      data-locations: classpath:demo_data.sql
      continue-on-error: false
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: delivery_project
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
jwt:
  token:
    secret: c2VjcmV0aWdpdWhvaWhvdWpvaWpiZ2p5dnViamg=
    accessToken: 3600000
    refreshToken: 2592000000